language: python
cache: pip

install: travis_retry pip install -U tox

script: tox
jobs:
  fast_finish: true

  include:
  - { python: '3.6', env: TOXENV=lint }
  - { python: '2.7', env: TOXENV=py27 }
  - { python: '3.5', env: TOXENV=py35 }
  - { python: '3.6', env: TOXENV=py36 }
  - { python: '3.7', env: TOXENV=py37, dist: xenial }
  - { python: '3.6', env: TOXENV=docs }

  - stage: PyPI Release
    if: tag IS present
    python: "3.6"
    env: []
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: sloria
      on:
        tags: true
      distributions: sdist bdist_wheel
      password:
        secure: gi6lzTgK4I42Is1Hzk1VZCSR3sIqAE2xqSc/xySuoJNZwMADIJNrjahW/CgfnIQYXSpYc8aya3B5p9+95Fdk88YQLrVm0e6EhJ2MXT5R9d/dmlKSEWRQQjlMduApq2AJKY/vhs+hxPuPL7kbuZaPMnY7p+D4JsrVPJfKM9IydrY=
